### ISSUE TITLE
Error on the new release 

### ISSUE THREAD

**Issue by trainguy68** [JMRI/website#452]
![264794504_599607661246304_3371784428100423665_n](https://user-images.githubusercontent.com/96700909/147419206-80c84026-a2e5-49ca-8605-8d54faf8bf48.jpg)
![264811299_982599392668658_7139353758910291404_n](https://user-images.githubusercontent.com/96700909/147419209-f90cf6e4-b90d-4831-a182-91713a370fab.jpg)
![264864192_945022719785816_1833547128848310370_n](https://user-images.githubusercontent.com/96700909/147419211-5fdf0957-d399-4df5-b215-10b912e6b6ee.jpg)

**Comment by danielb987** [comment]
@trainguy68 
Welcome to the JMRI project!
I suggest that you ask on the [JMRI users list](https://groups.io/g/jmriusers/topics) since there are more people there that can help you with your problem. [Join the list](https://groups.io/g/jmriusers/join)

If you ask there, you can refer to this issue.

Merry Christmas and a Happy New Year
Daniel
